#!/bin/sh

# PROVIDE: bazarr
# REQUIRE: LOGIN
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# bazarr_enable (bool):	Set to NO by default.
#				Set it to YES to enable bazarr.
# bazarr_dir: Directory where bazarr is installed
#             Default: /usr/local/bazarr

. /etc/rc.subr

name="bazarr"
rcvar="${name}_enable"

start_precmd=bazarr_precmd
stop_postcmd="Stopping bazarr.."

load_rc_config $name
: ${bazarr_enable:="NO"}
: ${bazarr_dir:="/usr/local/bazarr"}

command="/usr/local/bin/python3.8"
command_args="${bazarr_dir}/bazarr.py"
pidfile="${bazarr_dir}/bazarr.pid"

bazarr_precmd()
{
    export GIT_PYTHON_GIT_EXECUTABLE=/usr/local/bin/git
}

run_rc_command "$1"