#!/bin/sh

# PROVIDE: bazarr
# REQUIRE: LOGIN
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# bazarr_enable (bool):	Set to NO by default.
#				Set it to YES to enable bazarr.
# bazarr_dir: Directory where bazarr is installed
#             Default: /usr/local/bazarr
# bazarr_damon_user: User to start the deamon with
#                    Default: bazarr

. /etc/rc.subr

name="bazarr"
rcvar="${name}_enable"

start_precmd=bazarr_precmd
stop_postcmd=bazarr_postcmd

load_rc_config $name
: ${bazarr_enable:="NO"}
: ${bazarr_dir:="/usr/local/bazarr"}
: ${bazarr_daemon_user:="bazarr"}

python_bin="/usr/local/bin/python3.7"
bazarr_log="/var/log/bazarr.log"

pidfile="${bazarr_dir}/bazarr.pid"
command="/usr/sbin/daemon"
command_args="-o ${bazarr_log} -P ${pidfile} -u ${bazarr_daemon_user} ${python_bin} ${bazarr_dir}/bazarr.py"

bazarr_precmd()
{
    export GIT_PYTHON_GIT_EXECUTABLE=/usr/local/bin/git
}

bazarr_postcmd()
{
	killall -u ${bazarr_daemon_user} -INT
}

run_rc_command "$1"